#!/bin/bash

export LC_ALL=C
export DEBIAN_FRONTEND=noninteractive

export minimal_apt_get_install='apt-get install -y --no-install-recommends'

DISABLE_SYSLOG=1
#DISABLE_SSH=1

# Default services
# Set 1 to the service you want to disable
export DISABLE_SYSLOG=${DISABLE_SYSLOG:-0}
export DISABLE_SSH=${DISABLE_SSH:-0}
export DISABLE_CRON=${DISABLE_CRON:-0}

export etcServiceDir="/etc/minit"
export etcServicePreStartDir="/etc/minit_prestart"

export buildDir="/build"
export removeBuildDir="no"
export buildDirServices="/build/minitBaseSetup/services"